Assert-Contains "TASKS.md" "项目 Task 历史台账" "TASKS 当前/历史边界"
Assert-Contains "Docs\1-需求文档\README.md" "当前需求真源优先级.*README\.md.*状态\.md.*smoke" "需求文档入口真源优先级"
Assert-Contains "Docs\1-需求文档\功能清单.md" "历史功能快照" "功能清单历史边界"
Assert-Contains "Docs\1-需求文档\PRD-v3.md" "历史 PRD 说明.*当前版本.*状态\.md" "PRD-v3 历史边界"
Assert-Contains "Docs\1-需求文档\REQUIREMENTS-FINAL-v3.0.md" "历史需求基线说明.*当前 {{CURRENT_SPRINT}} 发布状态" "v3.0 需求基线历史边界"
Assert-Contains "Docs\2-产品文档\README.md" "产品文档入口" "产品文档入口存在"
Assert-Contains "Docs\2-产品文档\README.md" "不是发布状态单一真源" "产品文档入口发布边界"
Assert-Contains "Docs\2-产品文档\产品路线图.md" "历史路线图说明.*{{CURRENT_SPRINT}}" "产品路线图历史边界"
Assert-Contains "Docs\5-运维文档\README.md" "GitHub Actions 只作手动备用" "运维文档 GitHub Actions 手动边界"
Assert-Contains "Docs\5-运维文档\README.md" "git push.*不会自动出 APK" "运维文档 push 不自动出包边界"
Assert-Contains "Docs\4-测试文档\测试策略.md" "v3\.52\.0-E-weight-volume" "测试策略最新锚点"
Assert-NotContains "Docs\4-测试文档\测试策略.md" "/tmp/mimi-test|23 OK|33 个 test|v3\.1\+ 加 React Testing Library" "测试策略旧口径"
