$checks = @(
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = "handoff\s+卡（跨工具时）|交接卡给\s*(Claude Code|Codex)|Codex\s*战场"; Label = "decision-checkpoint 仍把工具当交接接手主语" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = "跨分支（项目 PM ↔ 增长 PM）|`{{APP_REPO_DIR}}/src/\*\*`\s*\|\s*❌|`{{APP_REPO_DIR}}/package\.json`[^\r\n]*\|\s*❌ 同上"; Label = "decision-checkpoint 路径/分支速查仍残留旧角色或准许角色写反" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-附录.md"; Pattern = "交接卡给\s*(Claude Code|Codex)|Codex\s*战场"; Label = "decision-checkpoint 附录示例仍把工具当交接接手主语" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-判定细则.md"; Pattern = "交接卡给\s*(Claude Code|Codex)|Codex\s*战场|外部工具战场"; Label = "decision-checkpoint 判定细则仍把工具当交接接手主语" },
    @{ Path = "操作系统/02_智能体/运营PM-运营咪咪.md"; Pattern = "三工具协作"; Label = "运营 PM playbook 仍以三工具作为协作主语" },
    @{ Path = "操作系统/02_智能体/运营PM-运营咪咪-附录.md"; Pattern = "三工具协作"; Label = "运营 PM 附录仍以三工具作为协作主语" },
    @{ Path = "能力资产/shared/品牌词典.md"; Pattern = "三工具协作"; Label = "品牌词典仍以三工具作为协作主语" },
    @{ Path = "操作系统/01_架构/角色边界.md"; Pattern = "四类外部角色分工（跨工具|\|\s*\*\*业务代码\*\*[^\r\n]*\|\s*\*\*Claude Code\*\*|\|\s*\*\*闭环验证\*\*[^\r\n]*\|\s*\*\*Codex\*\*|写测试代码\*\*\s*=\s*Claude Code|真机 smoke\s*=\s*Codex 专属"; Label = "角色边界仍把工具当责任主体" },
    @{ Path = "操作系统/01_架构/状态机.md"; Pattern = "接手者动手中（Claude Code / Codex / PM）"; Label = "状态机仍把工具和 PM 并列为接手者" },
    @{ Path = "操作系统/01_架构/元规则池.md"; Pattern = "Claude Code\s*战场"; Label = "元规则池仍把工具当战场主体" },
    @{ Path = "操作系统/01_架构/元规则池-候选.md"; Pattern = "Claude Code\s*战场"; Label = "元规则池候选仍把工具当战场主体" },
    @{ Path = "操作系统/01_架构/元规则池-附录.md"; Pattern = "Claude Code\s*战场"; Label = "元规则池附录仍把工具当战场主体" },
    @{ Path = "能力资产/tools/README.md"; Pattern = "{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类敏感|永久 C 类|永远不动)"; Label = "tools README 仍把 .env.local 本机配置写成 C 类" },
    @{ Path = "能力资产/tools/构建脚本.md"; Pattern = "{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类敏感|永久 C 类|永远不动)"; Label = "构建脚本文档仍把 .env.local 本机配置写成 C 类" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家.md"; Pattern = "{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类硬护栏|永远不能|永远不动)"; Label = "操作系统 PM playbook 仍把 .env.local 本机配置写成 C 类" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家-附录.md"; Pattern = "{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类硬护栏|永远不能|永远不动)"; Label = "操作系统 PM 附录仍把 .env.local 本机配置写成 C 类" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = '{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类|永远不动)|{{APP_REPO_DIR}}/\.env\.local`\s*/\s*API key 类'; Label = "decision-checkpoint 仍混淆 .env.local B 类与 API key 外传 C 类" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-判定细则.md"; Pattern = '{{APP_REPO_DIR}}/\.env\.local[^\r\n]*(C 类|永远不动)|{{APP_REPO_DIR}}/\.env\.local`\s*/\s*API key 类'; Label = "decision-checkpoint 判定细则仍混淆 .env.local B 类与 API key 外传 C 类" },
    @{ Path = "操作系统/01_架构/三类行为铁律.md"; Pattern = '打 git tag / 推 release'; Label = "三类行为铁律仍把常规版本 tag 与 release 混为 C 类" },
    @{ Path = "操作系统/01_架构/三类行为铁律-附录.md"; Pattern = '打 git tag / 推 release'; Label = "三类行为铁律附录仍把常规版本 tag 与 release 混为 C 类" },
    @{ Path = "操作系统/07_完整工作流/实施循环.md"; Pattern = 'force push / rebase / 删分支 / git tag / 推 release'; Label = "实施循环仍把常规版本 tag 写进 C 类硬护栏" },
    @{ Path = "操作系统/07_完整工作流/实施循环-附录.md"; Pattern = 'force push / rebase / 删分支 / git tag / 推 release'; Label = "实施循环附录仍把常规版本 tag 写进 C 类硬护栏" },
    @{ Path = "操作系统/07_完整工作流/实施循环.md"; Pattern = '开发 PM「实施者」DoD = .*条件性 commit/push|测试发布 PM「闭环者」.*当前执行载体：Claude Code'; Label = "实施循环仍让开发 PM 承担发布/commit push 或误写测试发布载体" },
    @{ Path = "操作系统/07_完整工作流/实施循环-附录.md"; Pattern = '开发 PM「实施者」DoD = .*条件性 commit/push|测试发布 PM「闭环者」.*当前执行载体：Claude Code'; Label = "实施循环附录仍让开发 PM 承担发布/commit push 或误写测试发布载体" }
)
