$checks = @(
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = "handoff\s+卡（跨工具时）|交接卡给\s*(Claude Code|Codex)|Codex\s*战场|handoff card \(when crossing tools\)|handoff card to\s*(Claude Code|Codex)|Codex\s*battlefield"; Label = "decision-checkpoint still names tools as handoff receivers" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = "跨分支（项目 PM ↔ 增长 PM）|`__CZXT_APP_REPO_DIR_REGEX__/src/\*\*`\s*\|\s*❌|`__CZXT_APP_REPO_DIR_REGEX__/package\.json`[^\r\n]*\|\s*❌ 同上|Cross-branch \(Project PM ↔ Growth PM\)|`__CZXT_APP_REPO_DIR_REGEX__/package\.json`[^\r\n]*\|\s*❌ Same as above"; Label = "decision-checkpoint path/branch reference retains obsolete roles or reverses permitted roles" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-附录.md"; Pattern = "交接卡给\s*(Claude Code|Codex)|Codex\s*战场|handoff card to\s*(Claude Code|Codex)|Codex\s*battlefield"; Label = "decision-checkpoint appendix examples still name tools as handoff receivers" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-判定细则.md"; Pattern = "交接卡给\s*(Claude Code|Codex)|Codex\s*战场|外部工具战场|handoff card to\s*(Claude Code|Codex)|Codex\s*battlefield|external-tool battlefield"; Label = "decision-checkpoint decision rules still name tools as handoff receivers" },
    @{ Path = "操作系统/02_智能体/运营PM-运营咪咪.md"; Pattern = "三工具协作|(?i:three-tool collaboration)"; Label = "Operations PM playbook still defines collaboration around three tools" },
    @{ Path = "操作系统/02_智能体/运营PM-运营咪咪-附录.md"; Pattern = "三工具协作|(?i:three-tool collaboration)"; Label = "Operations PM appendix still defines collaboration around three tools" },
    @{ Path = "能力资产/shared/品牌词典.md"; Pattern = "三工具协作|three-tool collaboration"; Label = "Brand dictionary still defines collaboration around three tools" },
    @{ Path = "操作系统/01_架构/角色边界.md"; Pattern = "四类外部角色分工（跨工具|\|\s*\*\*业务代码\*\*[^\r\n]*\|\s*\*\*Claude Code\*\*|\|\s*\*\*闭环验证\*\*[^\r\n]*\|\s*\*\*Codex\*\*|写测试代码\*\*\s*=\s*Claude Code|真机 smoke\s*=\s*Codex 专属|Four external role responsibilities \(cross-tool|\|\s*\*\*Business code\*\*[^\r\n]*\|\s*\*\*Claude Code\*\*|\|\s*\*\*Completion verification\*\*[^\r\n]*\|\s*\*\*Codex\*\*|Writing test code\*\*\s*=\s*Claude Code|Physical-device smoke\s*=\s*Codex only"; Label = "Role boundaries still assign responsibility to tools" },
    @{ Path = "操作系统/01_架构/状态机.md"; Pattern = "接手者动手中（Claude Code / Codex / PM）|Receiver at work \(Claude Code / Codex / PM\)"; Label = "State machine still lists tools alongside PMs as receivers" },
    @{ Path = "操作系统/01_架构/元规则池.md"; Pattern = "Claude Code\s*战场|Claude Code\s*battlefield"; Label = "Meta-rule pool still identifies tools as workspaces" },
    @{ Path = "操作系统/01_架构/元规则池-候选.md"; Pattern = "Claude Code\s*战场|Claude Code\s*battlefield"; Label = "Meta-rule candidates still identify tools as workspaces" },
    @{ Path = "操作系统/01_架构/元规则池-附录.md"; Pattern = "Claude Code\s*战场|Claude Code\s*battlefield"; Label = "Meta-rule appendix still identifies tools as workspaces" },
    @{ Path = "能力资产/tools/README.md"; Pattern = "__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类敏感|永久 C 类|永远不动|sensitive Class C|permanent Class C|never touch)"; Label = "tools README still classifies local .env.local configuration as Class C" },
    @{ Path = "能力资产/tools/构建脚本.md"; Pattern = "__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类敏感|永久 C 类|永远不动|sensitive Class C|permanent Class C|never touch)"; Label = "Build-script documentation still classifies local .env.local configuration as Class C" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家.md"; Pattern = "__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类硬护栏|永远不能|永远不动)|(?i:__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(hard Class C boundary|never permitted|never touch))"; Label = "Operating System PM playbook still classifies local .env.local configuration as Class C" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家-附录.md"; Pattern = "__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类硬护栏|永远不能|永远不动)|(?i:__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(hard Class C boundary|never permitted|never touch))"; Label = "Operating System PM appendix still classifies local .env.local configuration as Class C" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint.md"; Pattern = '__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类|永远不动)|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local`\s*/\s*API key 类|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(Class C|never touch)|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local`\s*/\s*API key category'; Label = "decision-checkpoint still confuses Class B .env.local configuration with Class C external API-key transmission" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-判定细则.md"; Pattern = '__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(C 类|永远不动)|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local`\s*/\s*API key 类|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local[^\r\n]*(Class C|never touch)|__CZXT_APP_REPO_DIR_REGEX__/\.env\.local`\s*/\s*API key category'; Label = "decision-checkpoint decision rules still confuse Class B .env.local configuration with Class C external API-key transmission" },
    @{ Path = "操作系统/01_架构/三类行为铁律.md"; Pattern = '打 git tag / 推 release|create git tag / publish release'; Label = "Three behavior classes rule still groups routine version tags with releases as Class C" },
    @{ Path = "操作系统/01_架构/三类行为铁律-附录.md"; Pattern = '打 git tag / 推 release|create git tag / publish release'; Label = "Three behavior classes appendix still groups routine version tags with releases as Class C" },
    @{ Path = "操作系统/07_完整工作流/实施循环.md"; Pattern = 'force push / rebase / 删分支 / git tag / 推 release|force push / rebase / delete branches / git tag / publish release'; Label = "Implementation loop still includes routine version tags in Class C hard limits" },
    @{ Path = "操作系统/07_完整工作流/实施循环-附录.md"; Pattern = 'force push / rebase / 删分支 / git tag / 推 release|force push / rebase / delete branches / git tag / publish release'; Label = "Implementation-loop appendix still includes routine version tags in Class C hard limits" },
    @{ Path = "操作系统/07_完整工作流/实施循环.md"; Pattern = '开发 PM「实施者」DoD = .*条件性 commit/push|测试发布 PM「闭环者」.*当前执行载体：Claude Code|Development PM “Implementer” DoD = .*conditional commit/push|Test and Release PM “Closer”.*current execution runtime: Claude Code'; Label = "Implementation loop still assigns release/commit push to Development PM or misidentifies the test-and-release adapter" },
    @{ Path = "操作系统/07_完整工作流/实施循环-附录.md"; Pattern = '开发 PM「实施者」DoD = .*条件性 commit/push|测试发布 PM「闭环者」.*当前执行载体：Claude Code|Development PM “Implementer” DoD = .*conditional commit/push|Test and Release PM “Closer”.*current execution runtime: Claude Code'; Label = "Implementation-loop appendix still assigns release/commit push to Development PM or misidentifies the test-and-release adapter" }
)

$appLiteral = [regex]::Escape('{{APP_REPO_DIR}}')
foreach ($check in $checks) {
  $check.Pattern = $check.Pattern.Replace('__CZXT_APP_REPO_DIR_REGEX__', $appLiteral)
}
