$script:P4kToolSubjectChecks = @(
    @{ Path = "能力资产/tools/README.md"; Pattern = 'Codex/CC\s*战场|Codex\s*战场|Claude Code\s*战场|(?i:Codex/CC\s*battlefield|Codex\s*battlefield|Claude Code\s*battlefield)'; Label = "tools README still defines responsibility boundaries as tool workspaces" },
    @{ Path = "能力资产/tools/构建脚本.md"; Pattern = 'Codex\s*战场|Claude Code\s*战场|PM / framework\s*战场|(?i:Codex\s*battlefield|Claude Code\s*battlefield|PM / framework\s*battlefield)'; Label = "Build-script documentation still defines responsibility boundaries as tool workspaces" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家.md"; Pattern = '测试代码 = Claude Code|构建配置 = Codex / Claude Code|给 Claude Code|Codex\s*战场|`tools/\*\*`|业务 ignore 留 Claude Code|让 Claude Code 改 CHANGELOG|实际 commit 由 Codex 顺手带|外部工具战场|→ Claude Code|→ Codex|(?i:Test code = Claude Code|Build configuration = Codex / Claude Code|handoff to Claude Code|Codex\s*battlefield|business ignore rules remain with Claude Code|have Claude Code edit CHANGELOG|Codex includes the actual commit|external-tool battlefield)'; Label = "Operating System PM playbook still assigns responsibility by tool name or uses obsolete tools paths" },
    @{ Path = "操作系统/02_智能体/操作系统PM-框架管家-附录.md"; Pattern = '测试代码 = Claude Code|构建配置 = Codex / Claude Code|给 Claude Code|Codex\s*战场|`tools/\*\*`|业务 ignore 留 Claude Code|让 Claude Code 改 CHANGELOG|实际 commit 由 Codex 顺手带|外部工具战场|→ Claude Code|→ Codex|(?i:Test code = Claude Code|Build configuration = Codex / Claude Code|handoff to Claude Code|Codex\s*battlefield|business ignore rules remain with Claude Code|have Claude Code edit CHANGELOG|Codex includes the actual commit|external-tool battlefield)'; Label = "Operating System PM appendix still assigns responsibility by tool name or uses obsolete tools paths" },
    @{ Path = "操作系统/02_智能体/产品PM-需求拆解者.md"; Pattern = 'Docs/2-技术文档|Claude Code\s*战场|Codex\s*战场|操作系统 PM\s*战场|`tools/\*\*`|__CZXT_APP_REPO_DIR_REGEX__/__tests__|→ Claude Code（外部）|Claude Code 实施|执行载体当前为 Claude Code|当前执行载体：Claude Code|(?i:Claude Code\s*battlefield|Codex\s*battlefield|Operating System PM\s*battlefield|→ Claude Code \(external\)|Claude Code implements|execution runtime is currently Claude Code|current execution runtime: Claude Code)'; Label = "Product PM playbook still has obsolete paths or tool-workspace responsibility wording" },
    @{ Path = "操作系统/02_智能体/产品PM-需求拆解者-附录.md"; Pattern = 'Docs/2-技术文档|Claude Code\s*战场|Codex\s*战场|操作系统 PM\s*战场|`tools/\*\*`|__CZXT_APP_REPO_DIR_REGEX__/__tests__|→ Claude Code（外部）|Claude Code 实施|执行载体当前为 Claude Code|当前执行载体：Claude Code|(?i:Claude Code\s*battlefield|Codex\s*battlefield|Operating System PM\s*battlefield|→ Claude Code \(external\)|Claude Code implements|execution runtime is currently Claude Code|current execution runtime: Claude Code)'; Label = "Product PM appendix still has obsolete paths or tool-workspace responsibility wording" },
    @{ Path = "操作系统/02_智能体/开发PM-实施者.md"; Pattern = '跨工具可换|(?i:interchangeable across tools)'; Label = "Development PM playbook should say tool adapters are interchangeable, not cross-tool interchangeability" },
    @{ Path = "操作系统/02_智能体/测试PM-质量门户.md"; Pattern = '给 Claude Code|Claude Code 或 Codex\s*战场|Codex\s*战场|Claude Code / Codex 该怎么跑测试|执行 = Claude Code / Codex|P4 Codex|Codex 闭环|→ Claude Code（外部）|→ Codex（外部）|受众 = Claude Code / Codex|Codex 跑真机 smoke|Claude Code 按 QA|Codex 按 QA|Claude Code / Codex 测试执行规范|Claude Code 写测试代码风格|(?i:handoff to Claude Code|Claude Code or Codex\s*battlefield|Codex\s*battlefield|how Claude Code / Codex should run tests|execution = Claude Code / Codex|Codex release completion|→ Claude Code \(external\)|→ Codex \(external\)|audience = Claude Code / Codex|Codex runs physical-device smoke|Claude Code follows QA|Codex follows QA|Claude Code / Codex test execution standard|Claude Code test-writing style)'; Label = "Test PM playbook still defines execution boundaries as tool workspaces" },
    @{ Path = "操作系统/02_智能体/测试PM-质量门户-附录.md"; Pattern = '给 Claude Code|Claude Code 或 Codex\s*战场|Codex\s*战场|Claude Code / Codex 该怎么跑测试|执行 = Claude Code / Codex|P4 Codex|Codex 闭环|→ Claude Code（外部）|→ Codex（外部）|受众 = Claude Code / Codex|Codex 跑真机 smoke|Claude Code 按 QA|Codex 按 QA|Claude Code / Codex 测试执行规范|Claude Code 写测试代码风格|(?i:handoff to Claude Code|Claude Code or Codex\s*battlefield|Codex\s*battlefield|how Claude Code / Codex should run tests|execution = Claude Code / Codex|Codex release completion|→ Claude Code \(external\)|→ Codex \(external\)|audience = Claude Code / Codex|Codex runs physical-device smoke|Claude Code follows QA|Codex follows QA|Claude Code / Codex test execution standard|Claude Code test-writing style)'; Label = "Test PM appendix still defines execution boundaries as tool workspaces" },
    @{ Path = "操作系统/02_智能体/测试发布PM-闭环者.md"; Pattern = '跨工具可换|(?i:interchangeable across tools)'; Label = "Test and Release PM playbook should say tool adapters are interchangeable, not cross-tool interchangeability" },
    @{ Path = "操作系统/01_架构/三类行为铁律.md"; Pattern = '仅允许绑定 Codex 发布闭环|Only within the Codex release workflow'; Label = "Three behavior classes rule still assigns version-tag responsibility to a tool instead of Test and Release PM" },
    @{ Path = "操作系统/07_完整工作流/git流程.md"; Pattern = '由 Codex 端 push|Claude Code 写完代码|Codex 出 APK|Codex 发布闭环|(?i:push from the Codex side|after Claude Code finishes the code|Codex builds the APK|Codex closes the release)'; Label = "Git workflow still assigns release/implementation responsibility by tool name" },
    @{ Path = "操作系统/07_完整工作流/实施循环.md"; Pattern = 'Codex / zlbdh 在 Windows|Cowork 端 DoD|Claude Code 端 DoD|Codex 端 DoD|(?i:Codex / zlbdh on Windows|Cowork-side DoD|Claude Code-side DoD|Codex-side DoD)'; Label = "Implementation loop still defines DoD responsibility by tool" },
    @{ Path = "操作系统/07_完整工作流/实施循环-附录.md"; Pattern = 'Codex / zlbdh 在 Windows|Cowork 端 DoD|Claude Code 端 DoD|Codex 端 DoD|(?i:Codex / zlbdh on Windows|Cowork-side DoD|Claude Code-side DoD|Codex-side DoD)'; Label = "Implementation-loop appendix still defines DoD responsibility by tool" },
    @{ Path = "操作系统/07_完整工作流/发布流程.md"; Pattern = 'Codex / zlbdh 装机跑|(?i:Codex / zlbdh installs and runs on the device)'; Label = "Release workflow still assigns primary smoke responsibility to Codex" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-判定细则.md"; Pattern = '外部工具战场|Codex\s*战场|Claude Code\s*战场|交接卡给\s*(Claude Code|Codex)|(?i:external-tool battlefield|Codex\s*battlefield|Claude Code\s*battlefield|handoff card to\s*(Claude Code|Codex))'; Label = "decision-checkpoint decision rules still assign responsibility by tool name" },
    @{ Path = "操作系统/01_架构/工具载体矩阵.md"; Pattern = '跨工具铁律|cross-tool mandatory rules'; Label = "Tool adapter matrix still describes the meta-rule pool as cross-tool mandatory rules" }
)

$appLiteral = [regex]::Escape('{{APP_REPO_DIR}}')
foreach ($check in $script:P4kToolSubjectChecks) {
  $check.Pattern = $check.Pattern.Replace('__CZXT_APP_REPO_DIR_REGEX__', $appLiteral)
}
