$script:P4kToolSubjectWorkflowChecks = @(
    @{ Path = "能力资产/tools/依赖矩阵.md"; Pattern = 'Claude Code 实施|Codex ship|(?i:Claude Code implementation)'; Label = "Dependency matrix still defines dependency implementation/ship stages by tool names" },
    @{ Path = "操作系统/01_架构/三类行为铁律-附录.md"; Pattern = '仅允许绑定 Codex 发布闭环|Only within the Codex release workflow'; Label = "Three behavior classes appendix still assigns version-tag responsibility to a tool instead of Test and Release PM" },
    @{ Path = "操作系统/07_完整工作流/decision-checkpoint-附录.md"; Pattern = '外部工具战场|(?i:external-tool battlefield)'; Label = "decision-checkpoint appendix still uses external-tool workspace terminology" },
    @{ Path = "操作系统/02_智能体/项目PM-咪咪.md"; Pattern = '外部工具回流|给外部工具|写交接卡给 Claude Code|写交接卡给 Codex|仍现行.*Claude Code|Claude Code/Codex 该怎么跑测试|(?i:return from external tools|handoff to external tools|write a handoff to Claude Code|write a handoff to Codex|still current.*Claude Code|how Claude Code/Codex should run tests)'; Label = "Project PM playbook still names tools as handoff recipients or current responsibility authorities" },
    @{ Path = "操作系统/02_智能体/项目PM-咪咪-附录.md"; Pattern = '外部工具回流|给外部工具|写交接卡给 Claude Code|写交接卡给 Codex|仍现行.*Claude Code|Claude Code/Codex 该怎么跑测试|(?i:return from external tools|handoff to external tools|write a handoff to Claude Code|write a handoff to Codex|still current.*Claude Code|how Claude Code/Codex should run tests)'; Label = "Project PM appendix still names tools as handoff recipients or current responsibility authorities" },
    @{ Path = "操作系统/02_智能体/技术PM-修复决策者.md"; Pattern = '路由外部工具|手术 = Claude Code|写交接卡给 Claude Code|受众 = Claude Code|→ Claude Code（外部）|Claude Code 按|Claude Code 实施规范|(?i:route to external tools|surgery = Claude Code|write a handoff to Claude Code|audience = Claude Code|→ Claude Code \(external\)|Claude Code follows|Claude Code implementation standards)'; Label = "Technical PM playbook still names tools as implementers or audiences" },
    @{ Path = "操作系统/02_智能体/技术PM-修复决策者-附录.md"; Pattern = '路由外部工具|手术 = Claude Code|写交接卡给 Claude Code|受众 = Claude Code|→ Claude Code（外部）|Claude Code 按|Claude Code 实施规范|(?i:route to external tools|surgery = Claude Code|write a handoff to Claude Code|audience = Claude Code|→ Claude Code \(external\)|Claude Code follows|Claude Code implementation standards)'; Label = "Technical PM appendix still names tools as implementers or audiences" },
    @{ Path = "操作系统/02_智能体/共享技能/INDEX.md"; Pattern = 'Codex 闭环前|Claude Code 完成代码后|(?i:before Codex release completion|after Claude Code finishes the code)'; Label = "Shared-skills index still triggers by tool stage" },
    @{ Path = "操作系统/02_智能体/共享技能/真机smoke清单.md"; Pattern = 'Codex 闭环前|Claude Code 完成代码后|HEAD hash 与 Codex 报告一致|(?i:before Codex release completion|after Claude Code finishes the code|HEAD matches the Codex report)'; Label = "Physical-device smoke checklist still triggers by tool stage or requires a Codex report" },
    @{ Path = "操作系统/02_智能体/共享技能/mount-stale防御.md"; Pattern = 'Codex push 后起手|Codex 报告 push 成功|HEAD hash 与 Codex 报告一致|(?i:start after Codex pushes|Codex reports a successful push|HEAD matches the Codex report)'; Label = "Mount-stale defense still requires Codex as the report author" },
    @{ Path = "操作系统/02_智能体/共享技能/PM自纠-trigger.md"; Pattern = '状态\.md 末尾 PM 切换轨迹加一行|(?i:append a PM transition row directly to the end of 状态\.md)'; Label = "PM self-correction shared skill still lets any PM write status history directly" },
    @{ Path = "操作系统/02_智能体/开发PM-实施者.md"; Pattern = '__CZXT_APP_REPO_DIR_REGEX__/src/__tests__/\*\.test\.js'; Label = "Development PM test-path allowlist remains too narrow" },
    @{ Path = "操作系统/02_智能体/项目PM-咪咪.md"; Pattern = '切产品 PM 写 PRD，再派开发 PM|(?i:switch to Product PM to write a PRD, then dispatch Development PM)'; Label = "Project PM playbook still forces bug fixes/existing implementation items through Product PM" },
    @{ Path = "操作系统/02_智能体/README.md"; Pattern = '按角色边界白名单动手 → 状态\.md 留痕|(?i:follow the role allowlist → record in 状态\.md)'; Label = "Agents README omits the writer responsible for status records" }
)

$appLiteral = [regex]::Escape('{{APP_REPO_DIR}}')
foreach ($check in $script:P4kToolSubjectWorkflowChecks) {
  $check.Pattern = $check.Pattern.Replace('__CZXT_APP_REPO_DIR_REGEX__', $appLiteral)
}
